### ISSUE TITLE
convert sicmutils build to deps.edn

### ISSUE THREAD

**Issue by sritchie** [sicmutils/sicmutils#205]
This will make it easier to consume 

At first, we can have a parallel deps.edn instead of fully porting the Leiningen project, but it probably makes sense to pin on one build system eventually.

For this first task we want:

- A working `deps.edn` that allows users to pull in sicmutils via a git dependency
- notes for how to run a repl
- how to trigger tests without leiningen

**Comment by sritchie** [comment]
@kloimhardt , this is the other task required to get us integrated with NextJournal (cc @mk).

**Comment by mk** [comment]
I see three possibilities:
1) just making it consumable as a git dep by adding a simple deps.edn (could even leave tests and dev out from the one I added in cb937c7893c96bde002bc3d9db0ff8b8bb53a340) at the cost of needing to specify deps in both project.clj & deps.edn. Would be very low risk and not mean a change of workflow
2) Using https://github.com/RickMoynihan/lein-tools-deps to keep using lein while specifying deps only in deps.edn. Looking at the open PRs like https://github.com/RickMoynihan/lein-tools-deps/pull/93 it might need some extra work
3) Dropping project.clj completely and converting everything to tools.deps. Probably the cleanest going forward but also most invasive because it means changing workflows. If we chose this option I think the first step would be to clean up `project.clj` a bit after agreeing on what can be removed (e.g. uberjar maybe?)

@sritchie do you have a preference?

**Comment by sritchie** [comment]
@mk , thanks for this summary and for looking into this. I think #1 is the best option for now, but I think 3 is the right medium term move.

If you see an obvious path for 3 and have some time, I'd take a PR for even the first cleanup phase; otherwise, let's do #1 immediately.

I haven't done a deps.edn move before. Do we need to do anything special to handle cljs vs shadow-cljs vs clj dependencies? I know we have a couple of npm packages (complex.js, fraction.js) that I've bundled into cljsjs packages. I've added them to my `shadow-cljs.edn` so that I can test the cljs build, but I'm not sure if there's some magic I need to do to declare them as deps.

Guidance here would be great if you've got a moment. Thanks, @mk !

**Comment by mk** [comment]
Ok, I’ll see that I do 1) soon, hopefully tomorrow. I’ll also see if we can get rid of cljsjs in favor of a deps.cljs: https://clojurescript.org/reference/packaging-foreign-deps

**Comment by mk** [comment]
Ops, should have closed this with #210.

**Comment by sritchie** [comment]
Closed by #517 .
