### ISSUE TITLE
Question: Can I assume that (value/= (simplify x) (simplify y)) "works" for all cases?

### ISSUE THREAD

**Issue by teodorlu** [sicmutils/sicmutils#225]
Hello!

Quick question. I'm observing that 

```clj
(value/= (simplify x) (simplify y))
```

"works" for my simple cases, like

```clj
(v/= (g/simplify (g/* 'x 'y))
     (g/simplify (g/* 'y 'x)))
;; => true
```

. But I'm hesitating to make this assumption general.

- Are there known counter-examples where `(value/= (simplify x) (simplify y))` should identify equality, but doesn't find it?
    - Does simplify "bottom out" to a canonical form?
- Are there property tests for `simplify`? I'm just finding example tests in `sicmutils.simplify-test`.

Thanks!

**Comment by sritchie** [comment]
@teodorlu yes, you should only need that for symbolic expressions, but that is a guarantee that we'd love to hold. I have some cases where, for example, the simplifier doesn't sort its outputs if there are sums or products. It's allowed to do this because complex and real * and + are commutative... otherwise we couldn't.

But this does get annoying when different sides of an equality return the same thing but for two terms switched.

No property based tests for that yet, but I think it's great to assume that it massages everything into canonical form.

Another thing you can do that WILL work in even more cases is subtract the sides and check for `zero?`.

**Comment by sritchie** [comment]
Hope this helps!

**Comment by teodorlu** [comment]
Thanks for the explanation about term sorting. I wasn't really sure whether I could expect that from the simplifier.

Good point about subtract + zero check!

Questions answered, closing :)

**Comment by teodorlu** [comment]
Note to self: remember simplify.

```clojure
(v/zero? (g/- (g/* 2 'meter 'meter)
              (g/* 'meter 'meter 2)))
;; => false

(v/zero? (g/simplify (g/- (g/* 2 'meter 'meter)
                          (g/* 'meter 'meter 2))))
;; => true
```
