### ISSUE TITLE
How to set up a minimal sicmutils browser repl?

### ISSUE THREAD

**Issue by kloimhardt** [sicmutils/sicmutils#271]
I get an error `No protocol method Value.zero? defined for type number: 1`, while the expected result is the number 435.

Description:
Following the Clojurescript [Quickstart](https://clojurescript.org/guides/quick-start), I set up this small [repository](https://github.com/kloimhardt/babashka-snipets) defining the following two functions:
```
(defn test-path [t] (st/up (+ (* 4 t) 7) (+ (* 3 t) 5) (+ (* 2 t) 1)))
(defn la [] (lg/Lagrangian-action (lg/L-free-particle 3) test-path 0 10))
``` 
and start a browser repl with 
```
clj --main cljs.main --compile scmtest.core --repl
```
at the repl, typing `(scmtest.core/test-path 1)` results in the expected `(up 11 8 3)`
but `(scmtest.core/la)` resulted in the above error. 

Do I miss a require somewhere or does deps.edn need an additional library?

**Comment by sritchie** [comment]
Hey @kloimhardt ! At first I thought that the problem was indeed a missing import, but you do of course have `sicmutils.value`, which implements the proper protocols for numbers:

https://github.com/sicmutils/sicmutils/blob/master/src/sicmutils/value.cljc#L159

I ran the code myself and actually got `0` as a result with no error, which is just as weird (with clj version `Version: 1.10.2.774`).

BUT! Error aside, I think the problem was that the functions you pasted in were using the core arithmetic operators instead of the generic one. Making this change gets me the proper result: https://github.com/kloimhardt/babashka-snipets/pull/1

Give it a try and let me know if that works for you!

**Comment by kloimhardt** [comment]
Gosh, indeed, I should have known about the generic arithmetic. Thank you very much. I now get the expected result 435.

But: if I change the first number 4 to the number 1, I get the following error:
```
cljs.user=> (scmtest.core/la1)
435
cljs.user=> (scmtest.core/la2)
Execution error (TypeError) at (<cljs repl>:1).
Cannot mix BigInt and other types, use explicit conversions
```

**Comment by sritchie** [comment]
@kloimhardt this is a subtle one - you've definitely tracked down a bug in the way all of the Clojurescript numerics hang together.

The problem you're running into is that `(lg/L-free-particle 3)` returns a `js/BigInt` or `Fraction` in Clojurescript... but all of the integration machinery assumes that you are passing a function that returns a `js/Number`!

The usual way to handle this is to pass `{:compile? true}`, which will turn your function-using-generics into a function that uses just doubles.

But I don't have an option to thread that through yet for `lg/Lagrangian-action`, whoops!

This should get you going in the meantime:

```clojure
(defn la2 []
  (lg/Lagrangian-action (comp sicmutils.util/double
                              (lg/L-free-particle 3))
                        test-path-2
                        0
                        10))
```

**Comment by sritchie** [comment]
That fix works because it forces the output of the `(lg/L-free-particle 3)` to be a `js/Number` instead of the `js/BigInt` or `Fraction` type that can pop out.

I really appreciate you kicking the tires on the Clojurescript stuff. I know it all "works" in theory, but we want a really nice REPL / user experience, and this is getting us there!

**Comment by kloimhardt** [comment]
I am glad I managed to actually kick a tire this time :-)
The fix works perfectly. I used the additional parser step of clj-tiles to implicitly apply the fix for now (and making it transparent by showing the Clojure code when augmented in this way).

**Comment by sritchie** [comment]
Excellent, thanks @kloimhardt ! I’ll ping the ticket when I get the other stuff merged.

**Comment by sritchie** [comment]
@kloimhardt just wanted to let you know that I checked in on this issue and, on the latest `main`, everything works great with no patches. I will release after a couple more tickets!

**Comment by kloimhardt** [comment]
@sritchie great! cannot wait to remove cruft from the clj-tiles parser when upgrading to sicmutils 0.21.0!
