### ISSUE TITLE
Modulo function does not work with symbol argument

### ISSUE THREAD

**Issue by pangloss** [sicmutils/sicmutils#272]
Even though `modulo` is present within the library, it's not exported by the env namespace and it also seems to be only a partial implementation since this basic use case doesn't work:

```clojure
(->infix (* 2 'x)) ; => "2 x"
(->infix (sicmutils.generic/modulo 2 'x)) ;; error
```

This seems like an oversight? I noticed the same issue with `remainder`.

I looked to see if I could simply implement the missing functionality and submit a PR, but after 10 minutes of searching I still couldn't figure out where that would be implemented.

**Comment by sritchie** [comment]
@pangloss it's definitely a bug that it's not exported into env - I'll get that fixed right away, thanks for the catch!

I currently only have `modulo` installed for functions, integers and `sicmutils.modint/ModInt` instances. Your question about modulo between symbols is, I think, related to sicmutils/placeholder#81 in this way (your design thoughts would be great here):

In the original `scmutils`, all "literal expressions", or symbols, are treated as (symbolic) complex numbers. There was SOME machinery in the library to specify that certain symbols were reals... but the general idea that you really want is the ability to make abstract vectors, matrices, reals, rationals, whatever, and have them only respond to the proper operations.

SO! That's why certain stuff is missing for symbols. `modulo` is (I'm pretty sure) only defined for integers, so it's not in there for real / complex symbols.

On the other hand, sicmutils/placeholder#81 is a weird case where of course we want to be able to write `(= 'a 'b)` and have that return a symbolic equality expression. But now the type is not Complex anymore! It's an abstract boolean. So what do you do? Make a new kind of "abstract boolean" probably, and then add symbolic control flow operators like `if` etc.

Anyway, just rambling now. Given that background, what do you think? Should `(modulo 2 'x)` return that form?

Quizzing @littleredcomputer too...

Thanks for reporting this!

**Comment by pangloss** [comment]
I hadn't ever encountered a complex modulo but Wolfram Alpha produces results for them and I found [this reference](https://mathworld.wolfram.com/ComplexModulus.html). On the other hand, modulo is definitely useful on real numbers.

**Comment by pangloss** [comment]
Without the benefit of any insight into the codebase or anything more than fragementary mathematical knowledge, would it make sense to have a "constrained type" or wrapper that could indicate that a symbol is some subset of the possible types? That could allow you to express that `(= 'a 'b)` is boolean, and that for `(mod 2 'x)`, `x` is one of `#{int real}`.

```clojure
(constrain '(= a b) #{::bool})
(constrain '(mod 2 x) #{:int :real})
```

**Comment by sritchie** [comment]
@pangloss complex modulus is a little different, and an important idea. That's installed under `magnitude`, for complex numbers:

```clojure
sicmutils.generic> (magnitude #sicm/complex "1+2i")
2.23606797749979
```

Also, your suggestion is definitely the right way to tackle this! It's a little involved but it's been on my list for a while. I'll make a discussion in the Discussions tab to start going over this design and we can push to make it happen.

I can see that I've made this behavior tough to add by hiding variables etc, but for now this incantation will add a `modulo` implementation that works the way you expect:

```clojure
(require '[sicmutils.abstract.number :as an])
(require '[sicmutils.numsymb :as sym])
(require '[sicmutils.value :as v])

(let [m @#'sym/symbolic-operator-table]
  (with-redefs [sym/symbolic-operator-table
                (assoc m 'modulo (fn [l r]
                                   (if (and (v/number? l)
                                            (v/number? r))
                                     (g/modulo l r)
                                     (list 'modulo l r))))]
    (#'an/defbinary g/modulo 'modulo)))
```

**Comment by sritchie** [comment]
What do you know, there's something sensible!

https://www.wolframalpha.com/input/?i=mod%2810%2C3.2%2B1i%29

Okay, this will be great. If you want to take a crack at it, you'll need to:

- add a function in [sicmutils.numsymb](https://github.com/sicmutils/sicmutils/blob/master/src/sicmutils/numsymb.cljc) that does the right thing for `modulo` and `remainder`. If there are numbers on BOTH sides, we should call `(g/modulo l r)`, or `(g/remainder l r)`, else build a list. Effectively just:

```clojure
(defn modulo [l r]
  (if (and (v/number? l)
           (v/number? r))
    (g/modulo l r)
    (list 'modulo l r)))
```

- Add the new functions as entries to [symbolic-operator-table](https://github.com/sicmutils/sicmutils/blob/master/src/sicmutils/numsymb.cljc#L405-L435)
- Somewhere around [here](https://github.com/sicmutils/sicmutils/blob/master/src/sicmutils/abstract/number.cljc#L191) in [sicmutils.abstract.number](https://github.com/sicmutils/sicmutils/blob/master/src/sicmutils/abstract/number.cljc#L191), add

```clojure
(defbinary g/modulo 'modulo)
(defbinary g/remainder 'remainder)
```

Finally, in a separate ticket/PR, we should back off [these lines](https://github.com/sicmutils/sicmutils/blob/master/src/sicmutils/numbers.cljc#L157-L161) in `sicmutils.numbers` to change `::v/native-integral` to `::v/real`. The catch is that these implementations only work for native types. So we'll have to test that, basically, `js/BigInt`, `goog.math.Long`, `goog.math.Integer` and `Fraction` all do SOMETHING right.

We can also install `g/modulo` in `sicmutils.complex` once one of us understands how it is supposed to work with complex numbers.

**Comment by pangloss** [comment]
Ok, I'll give it a try today.

**Comment by sritchie** [comment]
Great. Also let me know if you want to chat more about what you’re exploring in SICMUtils. It’s early days so use cases are always nice to see (beyond the big menu I’ve laid out for myself!)

**Comment by sritchie** [comment]
@pangloss ”play” is of course a very lovely use case!

**Comment by pangloss** [comment]
Mostly play and learning, but I also have in the back of my mind some possible applications in machine learning, though I'm not sure yet if this system can represent "AI tensors" and even if it could whether I'd be able to apply that to anything.

Playing a bit more with modulo [here](https://www.wolframalpha.com/input/?i=%5B%5B22%2C10%5D%2C%5B29%2C35%5D%5D+mod+%5B10%2C15%5D) I was able to get WolframAlpha to give me reasonable looking answers to `[[22,10],[29,35]] mod [10,15]`, which is interesting. I'm not sure if that means the modulo function would have to be installed in yet another place or whether this behaviour can be inferred?

**Comment by sritchie** [comment]
Interesting, looking around it looks like we have some fun work to do to extend modulo to different types: https://crypto.stackexchange.com/questions/29661/how-to-find-the-value-of-a-vector-modulo-a-basis-in-lattice-based-cryptography

We can take these one at a time, but to get that working we'd want to install modulo in `sicmutils.structure` too.

**Comment by pangloss** [comment]
Looking at the implementation of `sicmutils.generic/modulo`, it only works for integers, so I think it needs to be changed.

I think the following would be a better representation, except it looks like there is no generic floor function. This function should work for integers, reals and imaginary numbers if I can use floor, but on the other hand maybe it's better to use the built-in clojure `mod` function? Should this version which also supports imaginary numbers actually be implemented somewhere else?

```clojure
(defmethod modulo :default [a b]
  (sub a (mul b (floor (div a b)))))
```

**Comment by sritchie** [comment]
These changes that hit the numerics are a bit wide-ranging, but at great benefit to everything that builds on top. I think we'll want implementations in the following rough places:

- Symbols as a first pass, as described above
- complex numbers have separate implementations on the JVM and JS, so we'll need two entries here: https://github.com/sicmutils/sicmutils/blob/master/src/sicmutils/complex.cljc#L142. The JS implementation uses [complex.js](https://github.com/infusion/Complex.js/#complex-floorplaces0) and the JVM uses [apache-commons](https://commons.apache.org/proper/commons-math/javadocs/api-3.6/org/apache/commons/math3/complex/Complex.html).
- rational numbers are native on the JVM, but need [fraction.js](https://github.com/infusion/Fraction.js/) for Clojurescript. This means we only need an override on the JS side. That would go into [ratio.cljc](https://github.com/sicmutils/sicmutils/blob/master/src/sicmutils/ratio.cljc#L136).
- the only remaining real number to get is `js/BigInt` in Clojurescript. That would go into [numbers.cljc](https://github.com/sicmutils/sicmutils/blob/master/src/sicmutils/numbers.cljc).
- If we get all of those done, then we can change the types of [these three implementations](https://github.com/sicmutils/sicmutils/blob/master/src/sicmutils/numbers.cljc#L157-L161) to `::v/real`, since anything non-native will get caught their own implementations.

To be really pro, we can implement `g/modulo` and friends for

- the Clojure collections in [sicmutils.collections](https://github.com/sicmutils/sicmutils/blob/master/src/sicmutils/collection.cljc)
- `sicmutils.structure` and `sicmutils.matrix` open the door to [vector mod matrix](https://crypto.stackexchange.com/questions/26933/what-is-the-meaning-for-a-vector-mod-a-matrix-in-a-lattice) etc...

**Comment by sritchie** [comment]
@pangloss If you want to take a crack at any of those pieces that would be really awesome. That's how I would go about doing it, and I think that will make for a nice numeric stack.

Here's Clojure's `remainder` implementation for ratios, to help with the "fraction.js" implementation: https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/Numbers.java#L792-L799

**Comment by pangloss** [comment]
I'm looking at it now, but I'm currently stymied by a few things.

Firstly, I'm not sure which types I need to handle, and so am not sure what I can use to implement these things. 

Second, there is no `floor`, which I think I need for the modulo implementation I mentioned above. So I could add the following in `sicmutils.generic`, but am not sure if it's correct because I don't see much else here that's calling native math functions.

Or maybe these implementations are correct but go in another namespace... Still figuring it out.

```clojure
(defgeneric integer-part 1)
(defmethod integer-part :default [a]
  (Math/floor a))

(defgeneric floor 1)
(defmethod floor :default [a]
  (integer-part a))

(defgeneric ceiling 1)
(defmethod ceiling :default [a]
  (negate (floor (negate a)))
```

**Comment by sritchie** [comment]
Let's chat if you're on Slack? #sicmutils channel?
