### ISSUE TITLE
simplifier gets stuck for seemingly doable computation

### ISSUE THREAD

**Issue by adamhaber** [sicmutils/sicmutils#439]
Hi,

I'm trying to use the simplifier to do (element-wise) simplification of a certain matrix.
This is the relevant code:
```clojure
  (def data (matrix-by-rows (up 0 0) (up 0 1) (up 1 0) (up 1 1)))
  (def W (matrix-by-rows (up 'x11 'x12) (up 'x21 'x22)))
  (def transition_unnorm
    (->> (g/* (g/* data W) (g/transpose data))
         (matrix/fmap g/negate)
         (matrix/fmap g/exp)))
  (defn row-sums [mat]
    (->> (range 4)
         (map #(apply g/+ (matrix/nth-row mat %)))
         (map simplify)))

  (defn norm-vector [v c]
    (mapv #(g// % c) v))

  (def transition_norm
    (->> (mapv norm-vector transition_unnorm (row-sums transition_unnorm))
         (matrix/->Matrix 4 4)))
  (matrix/fmap ->TeX transition_norm)
  (def transition_norm_2
    (g/* transition_norm transition_norm))
```
here, `transition_norm` is a 4x4 Markov transition matrix (non-negative values, rows sums to one), and transition_norm_2 is its square. I've ran the simplifier on a single entry:
```clojure
(->> transition_norm_2
       second
       second
       simplify)
```
and it was still working after several hours. Is this the expected behavior?

Thanks!
Adam

**Comment by sritchie** [comment]
Okay, this is fixed by #440. Here is the final simplification: https://gist.github.com/sritchie/5002480d53b0353ef44a0b0a957fb167

The problem was that `(g/exp 0)` was returning 1.0, which forced the numbers into floating point. This made it extremely hard for the current polynomial GCD algorithm to find common factors when trying to combine different rational numbers.

Once I fixed that, your example hit the ONLY bug of its kind remaining in my 1200 line port of simplifier rules from Scheme... so thank you for hitting this!!

The simplifier ran well, but some of the entries hit the timeout on the polynomial GCD calculation. If you want to try it with a longer timeout, you can run:

```clojure
(binding [sicmutils.polynomial.gcd/*poly-gcd-time-limit* [10 :seconds]]
                 (clojure.pprint/pprint
                  (v/freeze (g/simplify transition_norm_2))))
```
